# TCL File Generated by Component Editor 20.1
# Mon Apr 05 05:48:24 UTC 2021
# DO NOT MODIFY


# 
# jpeg "jpeg" v1.0
#  2021.04.05.05:48:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module jpeg
# 
set_module_property DESCRIPTION ""
set_module_property NAME jpeg
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME jpeg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL jpeg
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file jpeg.sv SYSTEM_VERILOG PATH ../../rtl/jpeg.sv TOP_LEVEL_FILE
add_fileset_file ac_codes.bin OTHER PATH ../../rtl/ac_codes.bin
add_fileset_file byte_stuffer.sv SYSTEM_VERILOG PATH ../../rtl/byte_stuffer.sv
add_fileset_file code_shifter.sv SYSTEM_VERILOG PATH ../../rtl/code_shifter.sv
add_fileset_file dc_codes.bin OTHER PATH ../../rtl/dc_codes.bin
add_fileset_file dct_1d.sv SYSTEM_VERILOG PATH ../../rtl/dct_1d.sv
add_fileset_file dct_2d.sv SYSTEM_VERILOG PATH ../../rtl/dct_2d.sv
add_fileset_file huffman_coder.sv SYSTEM_VERILOG PATH ../../rtl/huffman_coder.sv
add_fileset_file jpeg_pipeline.sv SYSTEM_VERILOG PATH ../../rtl/jpeg_pipeline.sv
add_fileset_file ones_encoder.sv SYSTEM_VERILOG PATH ../../rtl/ones_encoder.sv
add_fileset_file pingpong_buffer.sv SYSTEM_VERILOG PATH ../../rtl/pingpong_buffer.sv
add_fileset_file q_table.hex HEX PATH ../../rtl/q_table.hex
add_fileset_file quantizer.sv SYSTEM_VERILOG PATH ../../rtl/quantizer.sv
add_fileset_file row_buffer.sv SYSTEM_VERILOG PATH ../../rtl/row_buffer.sv
add_fileset_file run_encoder.sv SYSTEM_VERILOG PATH ../../rtl/run_encoder.sv
add_fileset_file transpose_buffer.sv SYSTEM_VERILOG PATH ../../rtl/transpose_buffer.sv
add_fileset_file transpose_mem.sv SYSTEM_VERILOG PATH ../../rtl/transpose_mem.sv
add_fileset_file vdffe.sv SYSTEM_VERILOG PATH ../../rtl/vdffe.sv
add_fileset_file zigzag.sv SYSTEM_VERILOG PATH ../../rtl/zigzag.sv


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group jpeg
set_module_assignment embeddedsw.dts.name jpeg_enc
set_module_assignment embeddedsw.dts.vendor team4


# 
# display items
# 


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock_1
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly true
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts true
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitStates 0
set_interface_property slave readWaitTime 0
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 3
add_interface_port slave s_read read Input 1
add_interface_port slave s_write write Input 1
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_writedata writedata Input 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_1
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point clock_1
# 
add_interface clock_1 clock end
set_interface_property clock_1 clockRate 25000000
set_interface_property clock_1 ENABLED true
set_interface_property clock_1 EXPORT_OF ""
set_interface_property clock_1 PORT_NAME_MAP ""
set_interface_property clock_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_1 clk clk Input 1


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits WORDS
set_interface_property master associatedClock clock_1
set_interface_property master associatedReset reset_sink
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 0
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master m_waitrequest waitrequest Input 1
add_interface_port master m_address address Output 31
add_interface_port master m_read read Output 1
add_interface_port master m_write write Output 1
add_interface_port master m_readdata readdata Input 16
add_interface_port master m_writedata writedata Output 16
add_interface_port master m_byteenable byteenable Output 2


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_1
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

